### ISSUE TITLE
Settings.json path

### ISSUE THREAD

**Issue by benjyz** [ConsensusResearch/Scorex-Lagonaki#1]
Hi,

I tried running with start.sh, but a change is needed: with changing the script to the following it worked (scorex.Start does not exist):

```
#!/bin/sh

rm -rf data/

sbt clean

sbt compile

sbt start-script

cp settings.json target

sh -c 'target/start settings.json'
```

**Comment by kushti** [comment]
Hi Benjamin! Fixed start.sh in the repo with `cp settings.json target` . Are you sure about the last line? I think it start parameter is a name of a main class, so `sh -c 'target/start scorex.Start'` is correct

**Comment by benjyz** [comment]
I've made a pull-request to show where the error appears (for me).

**Comment by kushti** [comment]
Thanks, merged!
