### ISSUE TITLE
Docker container for Scorex-Lagonaki

### ISSUE THREAD

**Issue by istinspring** [ConsensusResearch/Scorex-Lagonaki#19]
Would be nice to have docker container. If accepted i can do it.

**Comment by kushti** [comment]
It would be awesome!

**Comment by istinspring** [comment]
Ok, trying to get in. Faced some issues, since there is compilation step (unlike python where you just push the sources inside the container and define entry point). But was able to build image and run it. Unfortunately it's not usable yet in this form, need to integrate it with SBT to:

+ automatically pull in dependencies and the correct path/name of target jars
+ ensure build dependencies match dev. runtime environment.

Also the image size is a bit large - 700mb and it takes time to build.

I'll try to do the following:

[ ] - pick SBT plugin: https://github.com/marcuslonnberg/sbt-docker or http://www.scala-sbt.org/sbt-native-packager/formats/docker.html
[ ] - build as small docker image as possible with Java environment to run compiled scorex.jar (i guess it's enough?)
[ ] - use SBT to generate Docker configs and images
[ ] - add ```docker``` task to build image from sbt console

**Comment by istinspring** [comment]
Guess i found nice solution for smaller image with java:

https://developer.atlassian.com/blog/2015/08/minimal-java-docker-containers/

guys suffered same problem:

> Official Java images have historically been mastodontic - cue picture above - I just tried "docker pull java" and I got an image of 816.4MB.

and they was able to reduce the size of image:

> fully functional Oracle Java 8 image weighing only 173Mb.

Few questions:

+ can Scorex run under OpenJDK or OracleJDK is required? 
+ Which Java to pick 7 or 8?

**Comment by istinspring** [comment]
And as far as i see data is persistent between sessions, correct?

> https://github.com/ConsensusResearch/Scorex-Lagonaki/blob/master/settings.json

```"datadir" : "/tmp/data",```

Is so it's required to expose /tmp folder to the docker container.

**Comment by istinspring** [comment]
https://github.com/ConsensusResearch/Scorex-Lagonaki/pull/22

**Comment by kushti** [comment]
merged
