### ISSUE TITLE
The only one logging solution

### ISSUE THREAD

**Issue by kushti** [ConsensusResearch/Scorex-Lagonaki#4]
Throughout the code there are few logging solutions being used, Logback / JUL, sometimes println even. Consider the only solution & use it everywhere

**Comment by benjyz** [comment]
I'd vote for SL4J, see: https://github.com/ConsensusResearch/Scorex-Lagonaki/commit/2fe126fd9cb6c4cc44dd0a01002733a643bb3cd7

**Comment by kushti** [comment]
Ok, going towards with that. Made ScorexLogging trait to reduce boilerplate https://github.com/ConsensusResearch/Scorex-Lagonaki/blob/master/src/main/scala/scorex/utils/ScorexLogging.scala
